#!/usr/bin/env bash

# Define the kubeconfig file
KUBECONFIG_FILE="kubeconfigs/personal.yaml"

# Check if the kubeconfig file exists
if [ ! -f "$KUBECONFIG_FILE" ]; then
  echo "Error: kubeconfig file not found: $KUBECONFIG_FILE"
  exit 1
fi

# Run kubectl with the specified kubeconfig file and passed arguments
kubectl --kubeconfig="$KUBECONFIG_FILE" "$@"