apiVersion: v1
kind: ConfigMap
metadata:
  name: cliper-config
  namespace: cliper
data:
  APP_NAME: "cliper"
  APP_URL: "https://cliper.gfarias.cl"
  APP_PORT: "8000"
  REDIS_PORT: "6379"
  REDIS_HOST: "redis"
  REDIS_PASSWORD: ""
  LOG_LEVEL: "debug"
  DATABASE_URI: "mongodb://mongo:27017/cliper"
  DATABASE_MAX_POOL_SIZE: "10"